AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Academic Word Game

Parameters:
  StageName:
    Type: String
    Default: prod
    Description: Stage Name (prod, dev, etc.)

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs14.x
    Environment:
      Variables:
        TABLE_NAME: !Ref AcademicWordsTable

Resources:
  AcademicWordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AcademicWords
      AttributeDefinitions:
        - AttributeName: english
          AttributeType: S
      KeySchema:
        - AttributeName: english
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GetWordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda
      Handler: handler.getWords
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AcademicWordsTable
      Events:
        GetWords:
          Type: Api
          Properties:
            Path: /api/words
            Method: get

  WordGameBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub academic-word-game-${AWS::AccountId}-${AWS::Region}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WordGameBucket
                - /*
      Bucket: !Ref WordGameBucket

Outputs:
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt 
      - WordGameBucket
      - WebsiteURL
  ApiURL:
    Description: URL of your API endpoint
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/